### ISSUE TITLE
Quick "getting started" section

### ISSUE THREAD

**Issue by mike-burns** [rst/positronic_net#2]
Add a section to the README with a line I can copy and paste into my sbt project.scala, maybe just below the mention of the installation instructions link.

**Comment by mike-burns** [comment]
Ah, it's more complicated than that because you also need to publish-local.

Any resistance to publishing this someplace public, as a snapshot?

**Comment by rst** [comment]
Well, the "installation instructions" link in the README actually points to
something now that's meant to include all the setup (it starts with "download
the Android SDK"), but this particular bit is left out.  The basics are to replace
the libraryDependencies one-liner from the g8 template with:

```
  libraryDependencies ++= Seq(
    "org.scalatest" %% "scalatest" % "1.6.1" % "test",
    "org.positronicnet" %% "positronicnetlib" % "0.3-SNAPSHOT"
  )
```

If you're adding it to an existing project which also has .jars in "lib", you
might also want to toss in this from my UmbrellaToday fork:

```
  proguardInJars in Android ++= ((file("lib") ** "*.jar") get)
```

since the 0.10/11 plugin seems not to include lib/*.jar in proguard inputs
unless you explicitly tell it to.

No objections to posting another public set of directions elsewhere (or
any other form of free publicity) --- though it can be tricky to check that
you haven't left out a step.

I'll probably update my instructions to say something about this over the
next few days, once I've figured out exactly what I want them to say.
(FWIW, the source is in my github pages repo at 
https://github.com/rst/rst.github.com --- patches welcome...)
