### ISSUE TITLE
Error with the Todo demo - Scala 2.8.2.final.

### ISSUE THREAD

**Issue by wpoosanguansit** [rst/positronic_net#4]
Hi,

I was not able to compile the sample as is with the project code.  So I just moved the code into my project which has the setup.  However, I get this weird and (I hope it is appropriate to say) hairy issue with byte code and delvik dec again.

01-07 11:58:32.413: D/dalvikvm(652): GC_CONCURRENT freed 249K, 4% free 10172K/10503K, paused 5ms+9ms
01-07 11:58:32.453: W/dalvikvm(652): VFY: unable to resolve static field 8417 (MODULE$) in Lscala/collection/mutable/HashMap$;
01-07 11:58:32.483: D/dalvikvm(652): VFY: replacing opcode 0x62 at 0x0000
01-07 11:58:32.483: W/dalvikvm(652): Unable to resolve superclass of Lorg/positronicnet/orm/Scope$$anonfun$count$1; (4190)
01-07 11:58:32.493: W/dalvikvm(652): Link of class 'Lorg/positronicnet/orm/Scope$$anonfun$count$1;' failed
01-07 11:58:32.493: E/dalvikvm(652): Could not find class 'org.positronicnet.orm.Scope$$anonfun$count$1', referenced from method org.positronicnet.orm.Scope$class.count
01-07 11:58:32.493: W/dalvikvm(652): VFY: unable to resolve new-instance 2324 (Lorg/positronicnet/orm/Scope$$anonfun$count$1;) in Lorg/positronicnet/orm/Scope$class;
01-07 11:58:32.503: D/dalvikvm(652): VFY: replacing opcode 0x22 at 0x0000
01-07 11:58:32.553: W/dalvikvm(652): Unable to resolve superclass of Lorg/positronicnet/orm/Scope$$anonfun$count$1; (4190)
01-07 11:58:32.553: W/dalvikvm(652): Link of class 'Lorg/positronicnet/orm/Scope$$anonfun$count$1;' failed
01-07 11:58:32.553: D/dalvikvm(652): DexOpt: unable to opt direct call 0x4290 at 0x02 in Lorg/positronicnet/orm/Scope$class;.count
01-07 11:58:32.553: W/dalvikvm(652): Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lcom/shopme/activity/TodoItem$;
01-07 11:58:32.563: D/AndroidRuntime(652): Shutting down VM
01-07 11:58:32.563: W/dalvikvm(652): threadid=1: thread exiting with uncaught exception (group=0x409c01f8)
01-07 11:58:32.643: E/AndroidRuntime(652): FATAL EXCEPTION: main
01-07 11:58:32.643: E/AndroidRuntime(652): java.lang.ExceptionInInitializerError
01-07 11:58:32.643: E/AndroidRuntime(652):  at com.myapp.activity.TodoItemsActivity$$anonfun$1.apply$mcV$sp(TodoItemsActivity.scala:55)
01-07 11:58:32.643: E/AndroidRuntime(652):  at org.positronicnet.ui.PositronicActivityHelpers$Handlers$$anonfun$runAll$1.apply(PositronicActivityHelpers.scala:89)
01-07 11:58:32.643: E/AndroidRuntime(652):  at org.positronicnet.ui.PositronicActivityHelpers$Handlers$$anonfun$runAll$1.apply(PositronicActivityHelpers.scala:89)
01-07 11:58:32.643: E/AndroidRuntime(652):  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:57)
01-07 11:58:32.643: E/AndroidRuntime(652):  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:43)
01-07 11:58:32.643: E/AndroidRuntime(652):  at org.positronicnet.ui.PositronicActivityHelpers$Handlers.runAll(PositronicActivityHelpers.scala:89)
01-07 11:58:32.643: E/AndroidRuntime(652):  at org.positronicnet.ui.PositronicActivityHelpers$class.onCreate(PositronicActivityHelpers.scala:109)
01-07 11:58:32.643: E/AndroidRuntime(652):  at com.myapp.activity.TodoItemsActivity.onCreate(TodoItemsActivity.scala:47)
01-07 11:58:32.643: E/AndroidRuntime(652):  at org.positronicnet.ui.PositronicActivityHelpers$class.onCreate(PositronicActivityHelpers.scala:101)
01-07 11:58:32.643: E/AndroidRuntime(652):  at com.myapp.activity.TodoItemsActivity.onCreate(TodoItemsActivity.scala:47)
01-07 11:58:32.643: E/AndroidRuntime(652):  at android.app.Activity.performCreate(Activity.java:4465)

I am not sure if there is any way to get around this?  Thank you for your help.

Watt P.

**Comment by rst** [comment]
From the look of those error messages, particularly "Could not find class...", the tree-shaker may be shaking out a bit too much, as I recall your setup.  (IIRC, Eclipse and tree-shaker.)  

For what it's worth, the superclass that it can't find seems to be a Scala runtime function:

```
 androiddev@pdp6:~/src/positronicnet$ sbt "project SampleTodo" console
 ...
 Welcome to Scala version 2.9.0.1 (OpenJDK Server VM, Java 1.6.0_20).
 Type in expressions to have them evaluated.
 Type :help for more information.

 scala> val k = Class.forName("org.positronicnet.orm.Scope$$anonfun$count$1")
 k: java.lang.Class[_] = class org.positronicnet.orm.Scope$$anonfun$count$1

 scala> k.getSuperclass
 res2: java.lang.Class[_ >: ?0] = class scala.runtime.AbstractFunction0$mcJ$sp
```

I'd expect the name of the missing superclass to be different for you, since you're using a different Scala version.  But it's clearly a component of the Scala runtime libraries for 2.9.0, and I'd expect the same with 2.8.2 as well.  And if your build setup is dropping those on the floor, it's hard for the library to compensate. 

Unfortunately, I'm not in a really good position to try to debug that sort of thing.  With access to your debug setup, the general approach I'd take would be to look for classes with the names it can't find in the output directories and .jar files, and see at what point they vanish. 

 (Of course, it does help to know what the superclass of the ...$anonfun$... thing is supposed to be, and ways of accessing that will also depend on your build setup.  If it has an equivalent to "sbt console", which runs the Scala read-eval-print loop with the app's Java bytecode on the classpath, then you can just use Java reflection as I did above, so that's one possible approach...)

**Comment by rst** [comment]
It belatedly occurred to me that I still have the Scala 2.8.2 test rig lying around from yesterday, so I can play the same game to determine the name of the superclass that's AWOL with that Scala version (presuming that the Scala version is the only thing the name depends on!).  So...

```
Welcome to Scala version 2.8.2.final (OpenJDK Server VM, Java 1.6.0_20).
Type in expressions to have them evaluated.
Type :help for more information.

scala> val k = Class.forName("org.positronicnet.orm.Scope$$anonfun$count$1")
k: java.lang.Class[_] = class org.positronicnet.orm.Scope$$anonfun$count$1

scala> k.getSuperclass
res0: java.lang.Class[_ >: ?0] = class scala.runtime.AbstractFunction0$mcL$sp
```

It's still probably better to doublecheck that the missing superclass has the same name in your environment...

**Comment by wpoosanguansit** [comment]
Thank you for your help. I find it not feasible to make sbt run in the eclipse project that I have. What a mess. That makes it difficult to get the console into the project. Also, in eclipse, the android plugin just prevents the console to attach from the scala ide plugin. So that blocks me out of having a repl. So out of desperation, I just had to opt for the least alternative which is pulling out your code into the project itself. Now things start to jell somewhat. At least the byte code hairball is not there. I am not a big Scala dev guy by any shot. But I really like to know who made the decision to change the byte code to be non compatible between versions and why. I want to make sure if they know what have they wrought and have him/her ban for life from designing. So sorry to let this out here. Again still in frustration but at least out of desperation for the moment. Cheers!

**Comment by rst** [comment]
Well, it's not the bytecode that's changing, so much as the runtime libraries.  And up to a certain point, changes are inevitable, just because it's impossible to get everything right the first time.

Still, they've been at this a while now, and at some point, things do have to settle down --- particularly since these incompatibilities have gotten to be a real headache for quite a few projects.  (ScalaTest is at this point shipping two "latest releases", one for Scala 2.8 and one for Scala 2.9.)  And the folks at Typesafe (Scala central) have promised that they'll be trying to get things to a state they can live with in their next release or two.

At any rate, since this issue seems to be more to do with build tooling than the project itself, I'm closing it...

**Comment by wpoosanguansit** [comment]
Soiry for the rant.  Thank you so much for your help and your great work.

Watt P.

On Jan 8, 2012, at 6:51 PM, Robert Thau reply@reply.github.com wrote:

Well, it's not the bytecode that's changing, so much as the runtime libraries.  And up to a certain point, changes are inevitable, just because it's impossible to get everything right the first time.

Still, they've been at this a while now, and at some point, things do have to settle down --- particularly since these incompatibilities have gotten to be a real headache for quite a few projects.  (ScalaTest is at this point shipping two "latest releases", one for Scala 2.8 and one for Scala 2.9.)  And the folks at Typesafe (Scala central) have promised that they'll be trying to get things to a state they can live with in their next release or two.

At any rate, since this issue seems to be more to do with build tooling than the project itself, I'm closing it...

---
